FROM python:3.7-slim
FROM jupyter/base-notebook

LABEL base_image="python:3.7;jupyter/minimal-notebook"
LABEL about.home="https://github.com/Clinical-Genomics/vogue"
LABEL about.documentation="https://vogue.readthedocs.io/"
LABEL about.license="MIT License (MIT)"

# Copy all project files
WORKDIR $HOME
COPY requirements-jupyter.txt ./requirements.txt

# Install vogue
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install jupyterthemes
RUN pip install --upgrade jupyterthemes
RUN pip install jupyter_contrib_nbextensions
RUN jupyter contrib nbextension install --user
