name: build and test docker containers

# Tigger building and testing container 

on:
  push:
    branches-ignore:
      - master
      - develop
    tags-ignore:
      - "**"
    paths:
      - 'Dockerfile'
      - 'Dockerfile_jupyter'
      - 'requirements.txt'
      - 'requirements-jupyter.txt'

jobs:
  main:
    name: Docker image build test 
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get branch name
        id: get_branch_name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Vogue only
        id: docker_build_test_vogue
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: false
          tags: clinicalgenomics/vogue:${{ steps.get_branch_name.outputs.branch }}
      - name: Build Jupyter only 
        id: docker_build_test_jupyter
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile_jupyter
          push: false
          tags: clinicalgenomics/vogue:${{ steps.get_branch_name.outputs.branch }}-jupyter
